Internal Server Error: /flashcards/recite_wordlist/19/0/1/
Traceback (most recent call last):
  File "E:\ANACONDA\envs\anki\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\ANACONDA\envs\anki\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\ANACONDA\envs\anki\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\ANACONDA\envs\anki\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\Anki\flashcards\views.py", line 335, in recite_wordlist
    recitedata.params = json.dumps(recitedata_params)
  File "E:\ANACONDA\envs\anki\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "E:\ANACONDA\envs\anki\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\ANACONDA\envs\anki\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\ANACONDA\envs\anki\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
"GET /flashcards/recite_wordlist/19/0/1/ HTTP/1.1" 500 102240
You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

You're accessing the development server over HTTPS, but it only supports HTTP.

"PRI * HTTP/2.0" 505 -
You're accessing the development server over HTTPS, but it only supports HTTP.

"PRI * HTTP/2.0" 505 -
